package org.beatengine.aibotdemo.aiintegration.tools;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.beatengine.aibotdemo.entity.Product;
import org.beatengine.aibotdemo.entity.ProductFields;

import java.io.Serializable;

@JsonPropertyOrder({ "id", "name", "description", "basePrice" })
public class ProductRecord implements ProductFields, Serializable {

    @JsonProperty(required = false)
    @JsonPropertyDescription("The unique id of a product generated by the database.")
    Long id;

    @JsonProperty(required = true)
    @JsonPropertyDescription("The name of a product.")
    String name;
    @JsonProperty(required = true)
    @JsonPropertyDescription("The description of a product.")
    String description;
    @JsonProperty(required = true)
    @JsonPropertyDescription("The base price of a product.")
    Float basePrice;

    public ProductRecord() {
    }

    public ProductRecord(Long id, String name, String description, float basePrice) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.basePrice = basePrice;
    }

    /**
     * Cast constructor
     * @param product The DB entity
     * */
    public ProductRecord(Product product) {
        this.id = product.getId();
        this.name = product.getName();
        this.description = product.getDescription();
        this.basePrice = product.getBasePrice();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getBasePrice() {
        return basePrice;
    }

    public void setBasePrice(float basePrice) {
        this.basePrice = basePrice;
    }
}
